networks:
  bridgenetwork:
    driver: bridge

services:
  webapp:
    build:
      context: ./webapp
    environment:
      NODE_ENV: production
    networks:
      - bridgenetwork
    ports:
      - 8000:8000
    depends_on:
      - applogic
  applogic:
    build:
      context: ./applogic
    environment:
      NODE_ENV: production
    networks:
      - bridgenetwork
    ports:
      - 8001:8001
    depends_on:
      - minioclient
  minioclient:
    build:
      context: ./minioclient
    environment:
      NODE_ENV: production
    networks:
      - bridgenetwork
    ports:
      - 8002:8002
    depends_on:
      - minioserver
  minioserver:
    image: minio/minio
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=secretpass
    networks:
      - bridgenetwork
    ports:
      - 9000:9000
      - 9090:9090     
    command: minio server --console-address ":9090" /data

  
